# Generated by Django 4.2.22 on 2025-06-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_profile_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proteinrecipes',
            options={'verbose_name': 'Protein Recipe', 'verbose_name_plural': 'Protein Recipes'},
        ),
    ]
