# Generated by Django 4.2.22 on 2025-06-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.proteinrecipes'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
