# Generated by Django 4.2.22 on 2025-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_text_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinrecipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
