# Generated by Django 4.2.22 on 2025-06-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0009_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proteinbite.proteinrecipes'),
        ),
    ]
