# Generated by Django 5.2.3 on 2025-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0010_alter_comment_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinrecipes',
            name='ingredients',
            field=models.TextField(default='No ingredients listed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proteinrecipes',
            name='method',
            field=models.TextField(default='No ingredients listed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proteinrecipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images/'),
        ),
    ]
