# Generated by Django 5.2.3 on 2025-06-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0011_proteinrecipes_ingredients_proteinrecipes_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinrecipes',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteinrecipes',
            name='meat_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proteinrecipes',
            name='portion_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
