# Generated by Django 5.2.3 on 2025-06-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0012_proteinrecipes_calories_proteinrecipes_meat_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinrecipes',
            old_name='portion_size',
            new_name='serves',
        ),
    ]
