# Generated by Django 3.2.25 on 2025-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0013_rename_portion_size_proteinrecipes_serves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinrecipes',
            name='image',
            field=models.ImageField(blank=True, default='picturecomingsoon.png', null=True, upload_to='media/recipe_images/'),
        ),
    ]
