# Generated by Django 3.2.25 on 2025-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinbite', '0014_alter_proteinrecipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinrecipes',
            name='image',
            field=models.ImageField(blank=True, default='picturecomingsoon.png', null=True, upload_to='recipe_images/'),
        ),
    ]
